name: Deployment

on:
  push:

  workflow_dispatch:

jobs:
  fabpot-security-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install security-checker
        run: |
          test -d local-php-security-checker || curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_amd64 --output local-php-security-checker
          chmod +x local-php-security-checker
          ./local-php-security-checker

  pest:
    runs-on: ubuntu-latest
    needs: [fabpot-security-checker]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          coverage: xdebug

      - name: Install composer packages
        run: |
          php -v
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: npm install
        run: |
          npm --version
          npm install
          npm run build

      - name: Execute tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cp .env.example .env
          php -v
          ./vendor/bin/pest --parallel --coverage-clover=coverage.xml
          bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
